### PR TITLE
Enhanced README.md

### PR DESCRIPTION
**Pull request by ayushsarode**
issue #5

### CODE REVIEW

**Comment by ayushsarode** [comment]
Kindly add ```hacktoberfest``` label,
Thank you!

**Comment by bbhupen** [comment]
> Kindly add `hacktoberfest` label, Thank you!

sure

**Review by bbhupen — COMMENTED** [review]
LGTM

**Review by bbhupen — APPROVED** [review]

**Comment by ayushsarode** [comment]
Hey @bbhupen, To be eligible for participation in Hacktoberfest, you need to ensure that you have added the ```hacktoberfest``` label to your repository's topics.

Example:
Screenshot 2023-10-07 213110

**Comment by bbhupen** [comment]
@ayushsarode 
got it 
will do it

**Pull request merged**
